version: "3"
services:
  node:
    restart: always
    build: .
    depends_on:
      - database
    environment:
      - MONGO_URL_DEV=mongodb://database:27017/dev-db
    ports:
      - 3000:3000
    volumes:
      - ./:/code
  database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
